site_name: FANTASTX Documentation
docs_dir: Docs
theme:
  name: material
  palette:
    - scheme: default
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
site_url: ""
use_directory_urls: false


# Repository
repo_name: MaterialEyes/fantastx
repo_url: https://github.com/MaterialEyes/fantastx

plugins:
  # - search # commented for 'build'
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
  - mkdocs-jupyter
    # execute: false
    # allow_errors: true
    # kernel_name: python3
  - git-revision-date

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MaterialEyes/fantastx

markdown_extensions:
  - tables
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true 

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - custom.css

site_url: https://fantastx.github.io/

nav:
  - Home: index.md
  - Installation: installation.md
  - FANTASTX YAML Preparation: YAML_PREP.md
  - Structural relaxation input files: energy.md
  - XANES YAML inputs: xanes.md
  - Running FANTASTX: run.md
  - Examples:
      - Grain Boundary TEM: gb_tem_example.md
      - Visualizing FANTASTX results: CdTe_Tellurene_Analysis.ipynb
      - Bulk PDF: iro2_pdf_example.md
      # - Molecule XANES: mol_xanes_example.md
  # - FAQs: FAQs.md
  - Citation: citation.md
  - API:
      - run_ops: run_ops-reference.md
      - inputs: inputs-reference.md
      - structure_record: structure_record-reference.md
      - initial_population: initial_population-reference.md
      - structure_operations: structure_operations-reference.md
      - energy: energy-reference.md
      - experimental_simulation: experimental_simulation-reference.md
      - selection: selection-reference.md
      - dominance: dominance-reference.md
      - epsilonSelection: epsilonSelection-reference.md
      - clusteredSelection: clusteredSelection-reference.md
      - fingerprinting: fingerprinting-reference.md
      - clustering: clustering-reference.md
      - distance_check: distance_check-reference.md
