#!/bin/bash
#PBS -l nodes=1:ppn=4:gen6
#PBS -l walltime=120:00:00
#PBS -l mem=16GB
#PBS -N FX_Al
#PBS -A cnm72851
#PBS -o job.out
#PBS -j oe
#PBS -m a

cd $PBS_O_WORKDIR

source activate ~/miniconda3/envs/fx_521

PYTHONUNBUFFERED=1 run_fx.py > job.log
