#!/bin/bash
#PBS -l nodes=1:ppn=4:gen6
#PBS -l walltime=10:00:00
#PBS -N gulpLiNMC
#PBS -A cnm72851
#PBS -o job.out
#PBS -j oe
#PBS -m a
 
cd $PBS_O_WORKDIR

module purge 
module load fftw3/3.3/impi impi intel lammps 

source activate ~/miniconda3/envs/fx_521

PYTHONUNBUFFERED=1 run_fx.py > job.log
